services:
  backend-deps:
    image: node:lts
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["npm", "install"]

  backend:
    container_name: finch-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - db
      - backend-deps

  db:
    image: postgres
    container_name: finch-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
